import type { Metadata } from "next";

import { Iosevka } from "@lib/fonts";
import StyledComponentsRegistry from "@/lib/registry";
import ThemeClientWrapper from "@/lib/theme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={"en"}>
      <body className={Iosevka.className}>
        <StyledComponentsRegistry>
          <ThemeClientWrapper>{children}</ThemeClientWrapper>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
